# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74c4222ba60defb0cb31a226e0b1d8b331d7aeb4cab6afc4629789d9a6e1e0d7a8f6ade828e1092ddb1a6da998088400dc429985db7217a1101d986cdeab9fe6
  stripe_publishable_key: pk_test_v2oZeypNMpwQ4Dyb3E99FUgg
  stripe_secret_key: sk_test_UfET8pM6suyALy0eeKUT7X6R
test:
  secret_key_base: daeeb9d50f09bf71747677feb38dc5e068c9ac939bed02fd8fca167aa7980ab068fdd14d3de231d00b3704bcd1582aa573ca1b0a0b3dc405cb9f3341cebb22e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
